nama: RDPserver

pada: alur kerja_dispatch

pekerjaan:

  membangun:

    berjalan-on: windows-terbaru

    menit-waktu habis: 9999

    Langkah:

    - Nama : Download Ngrok & NSSM

      lari: |

        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/ngrok.exe -OutFile ngrok.exe

        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/nssm.exe -OutFile nssm.exe

    - nama: Salin NSSM & Ngrok ke Direktori Windows.

      lari: | 

        salin nssm.exe C:\Windows\System32

        salin ngrok.exe C:\Windows\System32

    - nama: Hubungkan akun NGROK Anda

      jalankan: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      lingkungan:

        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}

    - nama: Unduh File Penting.

      lari: |

        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat

        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat

        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/loop.bat -OutFile loop.bat

    - nama: Buat file YML untuk NGROK.

      jalankan: mulai NGROK-AP.bat

    - nama: Aktifkan Akses RDP.

      lari: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0

        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1

    - nama: Buat Terowongan

      jalankan: sc start ngrok

    - nama: Hubungkan ke Ram RDP 2core-7GB Anda.

      jalankan: cmd /c NGROK-CHECK.bat

    - name: All Done! You can close Tab now! Maximum VM time:6h.

      run: cmd /c loop.bat
